#
# Copyright (c) Adrien BRICCHI and contributors. All rights reserved.
# Licensed under the MIT license. See LICENSE.md file in the project root for details.
#

language: bash
sudo: false
notifications:
    email:
        on_success: never
        on_failure: never

before_script:
    - cd ./unittests
    - curl -L "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/shunit2/shunit2-2.1.6.tgz" | tar zx

script:
    - bash unittests.sh

